services:
  - type: web
    name: cms-backend-spring-boot
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    autoDeployTrigger: commit
    envVars:
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRATION
        value: "86400000"
