spring.application.name=backend-spring-boot
# The Driver Class Name
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# The Connection URL (replace 'db_name' with your database name)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://root:BTmRvYpYnRgtxsRVrsoJScPdczyFiBpF@viaduct.proxy.rlwy.net:32957/railway}

# Database Credentials
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:BTmRvYpYnRgtxsRVrsoJScPdczyFiBpF}

# Hibernate properties (Optional but recommended)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# JWT Configuration
jwt.secret=${JWT_SECRET:secret_key_must_be_at_least_32_characters_long_for_security_purpose}
jwt.expiration=${JWT_EXPIRATION:86400000}
