spring.application.name=backend-spring-boot
# The Driver Class Name
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# The Connection URL (replace 'db_name' with your database name)
spring.datasource.url=jdbc:mysql://root:BTmRvYpYnRgtxsRVrsoJScPdczyFiBpF@viaduct.proxy.rlwy.net:32957/railway

# Database Credentials
spring.datasource.username=root
spring.datasource.password=BTmRvYpYnRgtxsRVrsoJScPdczyFiBpF

# Hibernate properties (Optional but recommended)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# JWT Configuration
jwt.secret=secret_key_must_be_at_least_32_characters_long_for_security_purpose
jwt.expiration=86400000